name: RunCodeRabbit
on:
  pull_request:
    branches:
      - master
jobs:
  coderabbit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CodeRabbit
        run: |
          npm install -g coderabbit-cli
          coderabbit analyze .
